### ISSUE TITLE
Feature Request - Label printer support

### ISSUE THREAD

**Issue by bseishen** [PoziWorld/Print-Waste-Minimizer#2]
Would it be an easy feature to have an option to print labels using a 4x6 label printer?

**Comment by PoziWorld** [comment]
Thank you for the suggestion! Will look into it.

**Comment by PoziWorld** [comment]
Sorry, probably still won't be able to look into it for another week or so. Will keep you posted.

**Comment by PoziWorld** [comment]
Sorry this is taking so long... Got multiple projects and all of them require attention. In a day or two, an important change will be completed for one of them, and then there should be some time to look into this.

Thank you for your understanding.

**Comment by PoziWorld** [comment]
1) Is there a particular website you would like this implemented for?

2) In the print window, have you tried adjusting the Scale field?
Setting it to Custom and lowering down the number?

---

It might not be easy to implement this, as sites like, for example, Amazon use different kinds of labels and different elements that are different in shape and size. 

I don't have a list of all such elements and, generally, I add support for a new kind only when I see it when I'm returning something myself.

I don't expect a company like Amazon would share such information with me, so I can implement this feature.

Or, I'd have to buy a lot of items and then return and hope I get a different kind of elements on the return label page.

**Comment by bseishen** [comment]
amazon.com, Its just usually the UPS return labels that are the issue. 

I have tried mucking around with the scaling, but the easiest solution is printing to a PDF and cropping in Photoshop

--
Ben S. Eishen
On 1/21/2020 10:37:07 PM, PoziWorld <notifications@github.com> wrote:
*
Is there a particular website you would like this implemented for?
*
In the print window, have you tried adjusting the Scale field?
Setting it to Custom and lowering down the number?
It might not be easy to implement this, as sites like, for example, Amazon use different kinds of labels and different elements that are different in shape and size.
I don't have a list of all such elements and, generally, I add support for a new kind only when I see it when I'm returning something myself.
I don't expect a company like Amazon would share such information with me, so I can implement this feature.
Or, I'd have to buy a lot of items and then return and hope I get a different kind of elements on the return label page.

**Comment by PoziWorld** [comment]
Next time I return something, I'll see what I can do.
